apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello-world
  namespace: tekton-pipelines
spec:
  steps:
    - name: echo
      image: alpine
      command:
        - echo
      args:
        - "Hello World"
