apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: calculate-sum
  namespace: default
spec:
  params:
    - name: a
      type: string
    - name: b
      type: string
  steps:
    - name: calculate
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        SUM=$(($(params.a) + $(params.b)))
        echo "Result: $(params.a) + $(params.b) = $SUM"
