apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows

resources:
  - cluster-destroy.yaml
  - provision-cluster-with-existing-fluxcd-repo.yaml
  - provision-cluster-with-new-fluxcd-repo.yaml
  - vm-destroy.yaml
  - vm-provision.yaml

