apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vm-destroy-pipeline
  namespace: argo-workflows
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: vm-name
        value: "new-gitops-vm"
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
  templates:
    - name: main
      steps:
        - - name: clone
            templateRef: { name: git-tasks, template: clone-repo }
            arguments:
              parameters:
                - name: repo-url
                  value: "github.com/anomaly51/proxmox-vms-terraform.git"
                - name: dest-path
                  value: "/workspace/repo"
        - - name: destroy
            templateRef: { name: tf-tasks, template: destroy-tf }
            arguments:
              parameters:
                - name: tf-dir
                  value: "/workspace/repo/envs/shared/{{workflow.parameters.vm-name}}"
        - - name: commit
            templateRef: { name: git-tasks, template: commit-changes }
            arguments:
              parameters:
                - name: repo-path
                  value: "/workspace/repo"
                - name: add-path
                  value: "envs/shared/{{workflow.parameters.vm-name}}/"
                - name: commit-message
                  value: "feat: terraform destroy VM {{workflow.parameters.vm-name}}"

