apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vm-provision-pipeline
  namespace: argo-workflows
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: vm-name
        value: "new-gitops-vm"
      - name: target-node
        value: "machine-1"
      - name: cores
        value: "4"
      - name: memory
        value: "4096"
      - name: disk-size
        value: "20"
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
  templates:
    - name: main
      steps:
        - - name: clone
            templateRef: { name: git-tasks, template: clone-repo }
            arguments:
              parameters:
                - name: repo-url
                  value: "github.com/anomaly51/proxmox-vms-terraform.git"
                - name: dest-path
                  value: "/workspace/repo"
        - - name: generate
            templateRef: { name: tf-tasks, template: generate-tf-vm }
            arguments:
              parameters:
                - name: vm-name
                  value: "{{workflow.parameters.vm-name}}"
                - name: target-node
                  value: "{{workflow.parameters.target-node}}"
                - name: cores
                  value: "{{workflow.parameters.cores}}"
                - name: memory
                  value: "{{workflow.parameters.memory}}"
                - name: disk-size
                  value: "{{workflow.parameters.disk-size}}"
        - - name: apply
            templateRef: { name: tf-tasks, template: apply-tf }
            arguments:
              parameters:
                - name: tf-dir
                  value: "/workspace/repo/envs/shared/{{workflow.parameters.vm-name}}"
        - - name: commit
            templateRef: { name: git-tasks, template: commit-changes }
            arguments:
              parameters:
                - name: repo-path
                  value: "/workspace/repo"
                - name: add-path
                  value: "envs/shared/{{workflow.parameters.vm-name}}/"
                - name: commit-message
                  value: "feat: terraform apply VM {{workflow.parameters.vm-name}}"

