apiVersion: v1
kind: Secret
metadata:
  name: capacitor-next
  namespace: flux-system
type: Opaque
stringData:
  LICENSE_KEY: "message laszlo at gimlet.io"
  SESSION_HASH_KEY: "base64:T2o4eXBEbWp6b0h2dWJxVXZyZ1h5cTh3ZnpQWjNNcWk="
  SESSION_BLOCK_KEY: "base64:WnBqOFh2Q3V0Mlk5cU1sS0J6YUQ4d0Y1R1pPZ0QxbWg="
  registry.yaml: |
    clusters:
    - id: in-cluster
      name: In-cluster
      apiServerURL: https://kubernetes.default.svc
      certificateAuthorityFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serviceAccount:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
