apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cluster-destroy-pipeline
  namespace: default
spec:
  params:
    - name: tf-repo-url
      type: string
      default: "github.com/anomaly51/proxmox-vms-terraform.git"
    - name: cluster-name
      type: string
      default: "new-k3s"
  tasks:
    - name: destroy-cluster
      taskSpec:
        steps:
          - name: clone
            image: alpine/git:v2.43.0
            env:
              - name: GIT_TOKEN_P1
                value: "ghp_"
              - name: GIT_TOKEN_P2
                value: "95do3C5ZrLwwvkIhLkyf4UERp8PFhW1yfyoM"
            script: |
              set -e
              git clone https://${GIT_TOKEN_P1}${GIT_TOKEN_P2}@$(params.tf-repo-url) /workspace/data/repo
          - name: destroy
            image: hashicorp/terraform:1.5.7
            env:
              - name: GIT_TOKEN_P1
                value: "ghp_"
              - name: GIT_TOKEN_P2
                value: "95do3C5ZrLwwvkIhLkyf4UERp8PFhW1yfyoM"
            script: |
              set -e
              git config --global url."https://${GIT_TOKEN_P1}${GIT_TOKEN_P2}@github.com/".insteadOf "https://github.com/"
              cd /workspace/data/repo/envs/shared/$(params.cluster-name)
              terraform init
              terraform destroy -auto-approve
          - name: commit
            image: alpine/git:v2.43.0
            env:
              - name: GIT_TOKEN_P1
                value: "ghp_"
              - name: GIT_TOKEN_P2
                value: "95do3C5ZrLwwvkIhLkyf4UERp8PFhW1yfyoM"
            script: |
              set -e
              cd /workspace/data/repo
              git config --global user.name "Tekton Pipeline"
              git config --global user.email "tekton@devops.local"
              git rm -rf envs/shared/$(params.cluster-name)/
              git commit -m "feat: terraform destroy K3s cluster $(params.cluster-name)"
              git push origin main

