apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tasks/infra-provision.yaml
  - tasks/gitops-repo-create.yaml
  - tasks/fluxcd-bootstrap.yaml
  - pipelines/provision-cluster-with-new-fluxcd-repo.yaml
  - pipelines/provision-cluster-with-existing-fluxcd-repo.yaml
  - cluster-destroy.yaml
  - pipelines/vm-provision.yaml
  - pipelines/vm-destroy.yaml
