apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cleanup-tasks
  namespace: argo-workflows
spec:
  templates:
    - name: cleanup-on-failure
      inputs:
        parameters:
          - name: cluster-name
          - name: repo-name
          - name: delete-repo
            default: "true"
      steps:
        - - name: terraform-destroy
            templateRef:
              name: tf-tasks
              template: destroy-tf
            arguments:
              parameters:
                - name: tf-dir
                  value: "/workspace/tf-repo/envs/shared/{{inputs.parameters.cluster-name}}"
        - - name: delete-gitops-repo
            template: delete-github-repo
            when: "{{inputs.parameters.delete-repo}} == true"
            arguments:
              parameters:
                - name: repo-name
                  value: "{{inputs.parameters.repo-name}}"

    - name: delete-github-repo
      inputs:
        parameters:
          - name: repo-name
      script:
        image: alpine:3.18
        command: [sh]
        env:
          - name: GIT_TOKEN_P1
            value: "ghp_"
          - name: GIT_TOKEN_P2
            value: "r4UyKZAyUmA7Nu7zGVFSSTMwxqKhvL2S4c6W"
        source: |
          set -e
          apk add --no-cache curl
          FULL_TOKEN="${GIT_TOKEN_P1}${GIT_TOKEN_P2}"
          curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: token $FULL_TOKEN" https://api.github.com/repos/anomaly51/{{inputs.parameters.repo-name}}
        volumeMounts:
          - name: workspace
            mountPath: /workspace

