apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flux-tasks
  namespace: argo-workflows
spec:
  templates:
    - name: bootstrap
      inputs:
        parameters:
          - name: cluster-name
          - name: github-owner
          - name: repo-name
          - name: master-node-ip
      script:
        image: dtzar/helm-kubectl:3.12
        command: [sh]
        env:
          - name: GIT_TOKEN_P1
            value: "ghp_"
          - name: GIT_TOKEN_P2
            value: "r4UyKZAyUmA7Nu7zGVFSSTMwxqKhvL2S4c6W"
        source: |
          set -e
          apk add --no-cache curl openssh-client
          # Fetch Kubeconfig via k3sup
          curl -sLS https://get.k3sup.dev | sh
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/id_ed25519
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACD5YK+hwQw+eyIBAEdg/nTJ4/Lv9iLdbqPTpKoH2lUIpwAAAJAa/POCGvzz
          ggAAAAtzc2gtZWQyNTUxOQAAACD5YK+hwQw+eyIBAEdg/nTJ4/Lv9iLdbqPTpKoH2lUIpw
          AAAEDIuAdzJk3z34U/O5FvZ4zh2JdiBcj2elF6RNyI0uFG6flgr6HBDD57IgEAR2D+dMnj
          8u/2It1uo9OkqgfaVQinAAAACnByb3htb3gtdm0BAgM=
          -----END OPENSSH PRIVATE KEY-----
          EOF
          chmod 600 ~/.ssh/id_ed25519
          k3sup install --skip-install --host {{inputs.parameters.master-node-ip}} --user root --ssh-key ~/.ssh/id_ed25519 --local-path /workspace/kubeconfig --context {{inputs.parameters.cluster-name}}

          # Flux Bootstrap
          export KUBECONFIG=/workspace/kubeconfig
          export GITHUB_TOKEN="${GIT_TOKEN_P1}${GIT_TOKEN_P2}"
          curl -s https://fluxcd.io/install.sh | bash
          flux bootstrap github \
            --owner={{inputs.parameters.github-owner}} \
            --repository={{inputs.parameters.repo-name}} \
            --branch=main \
            --path=./cluster \
            --personal=true
        volumeMounts:
          - name: workspace
            mountPath: /workspace
