apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-tasks
  namespace: argo-workflows
spec:
  templates:
    - name: clone-repo
      inputs:
        parameters:
          - name: repo-url
          - name: dest-path
            default: "/workspace/repo"
      script:
        image: alpine/git:v2.43.0
        command: [sh]
        env:
          - name: GIT_TOKEN_P1
            value: "ghp_"
          - name: GIT_TOKEN_P2
            value: "r4UyKZAyUmA7Nu7zGVFSSTMwxqKhvL2S4c6W"
        source: |
          set -e
          rm -rf {{inputs.parameters.dest-path}}
          git clone https://${GIT_TOKEN_P1}${GIT_TOKEN_P2}@{{inputs.parameters.repo-url}} {{inputs.parameters.dest-path}}
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: create-gitops-repo
      inputs:
        parameters:
          - name: cluster-name
          - name: template-url
            default: "github.com/anomaly51/gitops-template-fluxcd.git"
      outputs:
        parameters:
          - name: repo-name
            valueFrom:
              path: /tmp/repo-name.txt
      script:
        image: alpine/git:v2.43.0
        command: [sh]
        env:
          - name: GIT_TOKEN_P1
            value: "ghp_"
          - name: GIT_TOKEN_P2
            value: "r4UyKZAyUmA7Nu7zGVFSSTMwxqKhvL2S4c6W"
        source: |
          set -e
          apk add --no-cache curl
          FULL_TOKEN="${GIT_TOKEN_P1}${GIT_TOKEN_P2}"
          NEW_REPO_NAME="{{inputs.parameters.cluster-name}}-gitops"
          curl -s -X POST -H "Authorization: token $FULL_TOKEN" -d "{\"name\":\"${NEW_REPO_NAME}\", \"private\": true}" https://api.github.com/orgs/anomaly51/repos
          git clone https://${FULL_TOKEN}@{{inputs.parameters.template-url}} /workspace/template-repo
          cd /workspace/template-repo
          rm -rf .git
          find . -type f -name "*.yaml" -exec sed -i "s/{{CLUSTER_NAME}}/{{inputs.parameters.cluster-name}}/g" {} +
          git init
          git branch -M main
          git config --global user.name "Tekton Pipeline"
          git config --global user.email "tekton@devops.local"
          git add .
          git commit -m "chore: initialize cluster {{inputs.parameters.cluster-name}} from template"
          git remote add origin https://${FULL_TOKEN}@github.com/anomaly51/${NEW_REPO_NAME}.git
          git push -u origin main
          echo -n "${NEW_REPO_NAME}" > /tmp/repo-name.txt
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: commit-changes
      inputs:
        parameters:
          - name: repo-path
            default: "/workspace/tf-repo"
          - name: commit-message
          - name: add-path
      script:
        image: alpine/git:v2.43.0
        command: [sh]
        env:
          - name: GIT_TOKEN_P1
            value: "ghp_"
          - name: GIT_TOKEN_P2
            value: "r4UyKZAyUmA7Nu7zGVFSSTMwxqKhvL2S4c6W"
        source: |
          set -e
          cd {{inputs.parameters.repo-path}}
          git config --global user.name "Argo Workflow"
          git config --global user.email "argo@devops.local"
          git add {{inputs.parameters.add-path}}
          git commit -m "{{inputs.parameters.commit-message}}" || echo "No changes to commit"
          git push origin main
        volumeMounts:
          - name: workspace
            mountPath: /workspace

