apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tf-commit
  namespace: default
spec:
  params:
    - name: cluster-name
      type: string
  workspaces:
    - name: shared-data
  steps:
    - name: commit-and-push
      image: alpine/git:v2.43.0
      env:
        - name: GIT_TOKEN_P1
          value: "ghp_"
        - name: GIT_TOKEN_P2
          value: "r4UyKZAyUmA7Nu7zGVFSSTMwxqKhvL2S4c6W"
      script: |
        set -e
        cd $(workspaces.shared-data.path)/tf-repo
        git config --global user.name "Tekton Pipeline"
        git config --global user.email "tekton@devops.local"
        git add envs/shared/$(params.cluster-name)/
        git commit -m "feat: terraform apply and ansible init K3s cluster $(params.cluster-name)"
        git push origin main
